### PR TITLE
Add Tailwind example

### PR DESCRIPTION
**Pull request by kbrgl**
This PR adds an example that both uses Tailwind and describes how to set it up.

Screenshot 2023-06-16 at 6 33 54 PM

### CODE REVIEW

**Review by picklelo — APPROVED** [review]
nice

**Comment by milochen0418** [comment]
@kbrgl @picklelo 
The testing result on pc 0.1.34a0  is different from the expectation. 
- https://github.com/pynecone-io/pynecone-examples/pull/114#issuecomment-1596197612

Do I need to install another package? or just pynecone?

**Comment by milochen0418** [comment]
Screen Shot 2023-06-21 at 7 10 39 PM
I test it in 0.1.34. And error message is there.

**Comment by kbrgl** [comment]
Looks like nesting a <pre> inside a <p> is illegal. Lemme send a new PR with a fix...

**Pull request merged**
