### PR TITLE
Pr alpha test 0.1.33a1

### PR DESCRIPTION
**Pull request by milochen0418**
(Just for testing and put testing result on this pr page, plz don't merge)

**It's still in the testing for every example code**
According to the issue https://github.com/pynecone-io/pynecone-examples/issues/55
Update requriement.txt for latest version `pynecone==0.1.33a1` on PyPI 

The testing task is the following.
- [x] chatroom --critical bug
- [x]  clock 
- [x]  counter 
- [x]  crm  
- [x]  dalle 
- [x]  fragments  
- [x]  gpt 
- [x]  nba 
- [x]  quiz  
- [x]  sales  
- [x]  snakegame 
- [x]  todo 
- [x]  translator 
- [x]  traversal  
- [x] twitter  
- [x] upload 

In this Alpha-testing, there are new critical bug on `chatroom`, `clock`, `crm`, `fragments`, `gpt`, `nba`, `sales`, `snakegame` , `translator`(See the comment), `twitter`

The box with the check icon is the code we have done the testing for `pynecone==0.1.33a1`

**We have the bugs on these example: ... ** 

#### 0.1.33a1

New bugs

Old bugs
- https://github.com/pynecone-io/pynecone-examples/issues/62 `0.1.28`, `0.1.29`, `0.1.30`, `0.1.31`, `0.1.32`
- https://github.com/pynecone-io/pynecone-examples/issues/65 `0.1.29`, `0.1.30`, `0.1.31`, `0.1.32`
- https://github.com/pynecone-io/pynecone-examples/issues/80 `0.1.32`
- https://github.com/pynecone-io/pynecone-examples/issues/81 `0.1.32`
- https://github.com/pynecone-io/pynecone-examples/issues/83 `0.1.32`
- https://github.com/pynecone-io/pynecone-examples/issues/86 `0.1.32`
- https://github.com/pynecone-io/pynecone-examples/issues/87 `0.1.32`
- https://github.com/pynecone-io/pynecone-examples/issues/88 `0.1.31`, `0.1.32`

Bug solved
...

### My Testing Environment
I run all example codes by the following one-line command.   [one-line cmd ??  doc --help](https://hackmd.io/@milochen0418/pctest-0-1-29-script)
```
pip install -r requirements.txt && rm -f pynecone.db && rm -rf .web && for i in $(find ./ | grep __pycache__$); do rm -rf $i; done && echo -e "\033[1;92mMy Testing Environment\033[0m" && echo -e "\t"OS $(uname) $(uname -r) && echo -e "\t"Pynecone $(pc version) && echo -e "\t"$(python --version) && echo -e "\t"Node $(node --version) && echo -e "\t"Bun $(~/.bun/bin/bun --version) && pc init && pc run --loglevel=debug
```

And the test environment is 
```
My Testing Environment
        OS Darwin 22.4.0
        Pynecone 0.1.33a1
        Python 3.11.3
        Node v16.8.0
        Bun 0.5.9
```

On my computer, my Python version is 3.11.3. 
If some examples here cannot run well, you can use `python 3.11.3`

### The related issues that have been close from these PR updating
`None`

### CODE REVIEW

**Comment by milochen0418** [comment]
chatroom example: cannot change nick name. 
```
Traceback (most recent call last):
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/lib/python3.11/site-packages/pynecone/state.py", line 693, in _process_event
    events = await fn(**payload)
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/git/py-webapp/chatroom/chatroom/chatroom.py", line 33, in nick_change
    await broadcast_nicks()
  File "/Users/milochen/git/py-webapp/chatroom/chatroom/chatroom.py", line 117, in broadcast_nicks
    await broadcast_event("state.set_nicks", payload=dict(nicks=nicks))
  File "/Users/milochen/git/py-webapp/chatroom/chatroom/chatroom.py", line 94, in broadcast_event
    update = await state._process(
             ^^^^^^^^^^^^^^^^^^^^^
TypeError: object async_generator can't be used in 'await' expression
```

**Comment by picklelo** [comment]
Got it, this feature has the `yield` feature to allow for multiple event returns - it changes the API of the `state._process` function so this is expected. We will have to update the chatroom example.

**Comment by milochen0418** [comment]
## CRM example 
**New Bug**
pc run failed with the following error message
```
Traceback (most recent call last):
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/bin/pc", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/lib/python3.11/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/lib/python3.11/site-packages/typer/main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/lib/python3.11/site-packages/pynecone/pc.py", line 126, in run
    app = prerequisites.get_app()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/lib/python3.11/site-packages/pynecone/utils/prerequisites.py", line 104, in get_app
    return __import__(module, fromlist=(constants.APP_VAR,))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/git/py-webapp/crm/crm/crm.py", line 11, in <module>
    app.compile()
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/lib/python3.11/site-packages/pynecone/app.py", line 417, in compile
    compiler.compile_page(
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/lib/python3.11/site-packages/pynecone/compiler/compiler.py", line 149, in wrapper
    path, code = fn(*args)
                 ^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/lib/python3.11/site-packages/pynecone/compiler/compiler.py", line 220, in compile_page
    code = _compile_page(component, state, connect_error_component)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/lib/python3.11/site-packages/pynecone/compiler/compiler.py", line 84, in _compile_page
    imports = utils.merge_imports(DEFAULT_IMPORTS, component.get_imports())
                                                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/lib/python3.11/site-packages/pynecone/components/component.py", line 516, in get_imports
    self._get_imports(), *[child.get_imports() for child in self.children]
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/lib/python3.11/site-packages/pynecone/components/component.py", line 516, in <listcomp>
    self._get_imports(), *[child.get_imports() for child in self.children]
                           ^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/lib/python3.11/site-packages/pynecone/components/component.py", line 516, in get_imports
    self._get_imports(), *[child.get_imports() for child in self.children]
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/lib/python3.11/site-packages/pynecone/components/component.py", line 516, in <listcomp>
    self._get_imports(), *[child.get_imports() for child in self.children]
                           ^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/lib/python3.11/site-packages/pynecone/components/component.py", line 516, in get_imports
    self._get_imports(), *[child.get_imports() for child in self.children]
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/lib/python3.11/site-packages/pynecone/components/component.py", line 516, in <listcomp>
    self._get_imports(), *[child.get_imports() for child in self.children]
                           ^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/lib/python3.11/site-packages/pynecone/components/component.py", line 516, in get_imports
    self._get_imports(), *[child.get_imports() for child in self.children]
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/lib/python3.11/site-packages/pynecone/components/component.py", line 516, in <listcomp>
    self._get_imports(), *[child.get_imports() for child in self.children]
                           ^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/lib/python3.11/site-packages/pynecone/components/component.py", line 516, in get_imports
    self._get_imports(), *[child.get_imports() for child in self.children]
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/lib/python3.11/site-packages/pynecone/components/component.py", line 516, in <listcomp>
    self._get_imports(), *[child.get_imports() for child in self.children]
                           ^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/lib/python3.11/site-packages/pynecone/components/component.py", line 516, in get_imports
    self._get_imports(), *[child.get_imports() for child in self.children]
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/lib/python3.11/site-packages/pynecone/components/component.py", line 516, in <listcomp>
    self._get_imports(), *[child.get_imports() for child in self.children]
                           ^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/lib/python3.11/site-packages/pynecone/components/component.py", line 516, in get_imports
    self._get_imports(), *[child.get_imports() for child in self.children]
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/lib/python3.11/site-packages/pynecone/components/component.py", line 516, in <listcomp>
    self._get_imports(), *[child.get_imports() for child in self.children]
                           ^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/lib/python3.11/site-packages/pynecone/components/component.py", line 516, in get_imports
    self._get_imports(), *[child.get_imports() for child in self.children]
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/lib/python3.11/site-packages/pynecone/components/component.py", line 516, in <listcomp>
    self._get_imports(), *[child.get_imports() for child in self.children]
                           ^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/lib/python3.11/site-packages/pynecone/components/component.py", line 516, in get_imports
    self._get_imports(), *[child.get_imports() for child in self.children]
    ^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/lib/python3.11/site-packages/pynecone/components/navigation/link.py", line 30, in _get_imports
    return {**super()._get_imports(), **NextLink(href=self.href)._get_imports()}
                                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/lib/python3.11/site-packages/pynecone/components/component.py", line 157, in __init__
    raise TypeError(
TypeError: Invalid var passed for prop href, expected type pynecone.vars.Var[str], got value None of type <class 'NoneType'>.
```

**Comment by milochen0418** [comment]
## fragments 
**New Bug**
pc run failed with the following error message
```
Traceback (most recent call last):
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/bin/pc", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/lib/python3.11/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/lib/python3.11/site-packages/typer/main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/lib/python3.11/site-packages/pynecone/pc.py", line 126, in run
    app = prerequisites.get_app()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/lib/python3.11/site-packages/pynecone/utils/prerequisites.py", line 104, in get_app
    return __import__(module, fromlist=(constants.APP_VAR,))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/git/py-webapp/fragments/fragments/fragments.py", line 60, in <module>
    app.compile()
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/lib/python3.11/site-packages/pynecone/app.py", line 417, in compile
    compiler.compile_page(
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/lib/python3.11/site-packages/pynecone/compiler/compiler.py", line 149, in wrapper
    path, code = fn(*args)
                 ^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/lib/python3.11/site-packages/pynecone/compiler/compiler.py", line 220, in compile_page
    code = _compile_page(component, state, connect_error_component)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/lib/python3.11/site-packages/pynecone/compiler/compiler.py", line 84, in _compile_page
    imports = utils.merge_imports(DEFAULT_IMPORTS, component.get_imports())
                                                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/lib/python3.11/site-packages/pynecone/components/component.py", line 516, in get_imports
    self._get_imports(), *[child.get_imports() for child in self.children]
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/lib/python3.11/site-packages/pynecone/components/component.py", line 516, in <listcomp>
    self._get_imports(), *[child.get_imports() for child in self.children]
                           ^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/lib/python3.11/site-packages/pynecone/components/component.py", line 516, in get_imports
    self._get_imports(), *[child.get_imports() for child in self.children]
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/lib/python3.11/site-packages/pynecone/components/component.py", line 516, in <listcomp>
    self._get_imports(), *[child.get_imports() for child in self.children]
                           ^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/lib/python3.11/site-packages/pynecone/components/component.py", line 516, in get_imports
    self._get_imports(), *[child.get_imports() for child in self.children]
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/lib/python3.11/site-packages/pynecone/components/component.py", line 516, in <listcomp>
    self._get_imports(), *[child.get_imports() for child in self.children]
                           ^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/lib/python3.11/site-packages/pynecone/components/component.py", line 516, in get_imports
    self._get_imports(), *[child.get_imports() for child in self.children]
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/lib/python3.11/site-packages/pynecone/components/component.py", line 516, in <listcomp>
    self._get_imports(), *[child.get_imports() for child in self.children]
                           ^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/lib/python3.11/site-packages/pynecone/components/component.py", line 516, in get_imports
    self._get_imports(), *[child.get_imports() for child in self.children]
    ^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/lib/python3.11/site-packages/pynecone/components/navigation/link.py", line 30, in _get_imports
    return {**super()._get_imports(), **NextLink(href=self.href)._get_imports()}
                                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/milochen/anaconda3/envs/pynecone-alpha-test-0-1-33a1/lib/python3.11/site-packages/pynecone/components/component.py", line 157, in __init__
    raise TypeError(
TypeError: Invalid var passed for prop href, expected type pynecone.vars.Var[str], got value None of type <class 'NoneType'>.
```

**Comment by milochen0418** [comment]
## nba example 
**New Bug**
1. nba example is halting very long time for unknown reason. but sometimes is fast
Screenshot 2023-06-06 at 11 43 43 PM

2. Menu -> download 2D make the function of `pc.select` failed. the graph will not change after you change the option.

Screenshot 2023-06-06 at 11 51 44 PM

pc.select function works correctly in the normal way, but it will not work after you find Menu and click 20Dataset
What

**Comment by milochen0418** [comment]
## sales example

**New Bug**
The bottom two buttons of the onboarding page doesn't work after click.
Screenshot 2023-06-07 at 12 38 47 AM
So we cannot Submit customer and cannot go back to the home page by click the 2-lines button 

But we can click the right-top to switch page.

**Comment by milochen0418** [comment]
## snakegame example
**New Bug**
Screenshot 2023-06-07 at 12 43 54 AM
When we play snakegame... 
It will stop by some unknown reason. then we cannot use the page to change UI anymore.
But we can refresh page and play it again. 

But you can play it to stop again soon.

**Comment by milochen0418** [comment]
## translator example
**New Bug**
The basic form cannot be used well. 
Just post to translate first time. 
Try to change option on pc.select but failed.
Because no any GUI change happened on `pc.select`  component if you select another option.

I record the bug on this youtube
https://youtube.com/shorts/1_ICvEpEI44?feature=share

**Comment by milochen0418** [comment]
## twitter example
**I never test it on 0.1.32, but in the Alpha test 0.1.33a1, we have the following bug**
After click any one of button, you cannot see anything happened.

**Comment by milochen0418** [comment]
Close this PR because it has upgraded to 0.1.33

**Pull request closed without merging**
