### PR TITLE
[Fix #84 #92] add onload to set default status for checkbox and radio_group

### LINKED ISSUE #84: quiz example: Question 3 read wrong input
Screenshot 2023-05-30 at 9 12 37 AM

Screenshot 2023-05-30 at 9 12 44 AM

### PR DESCRIPTION
**Pull request by milochen0418**
Solve this issue 
- https://github.com/pynecone-io/pynecone-examples/issues/84
- https://github.com/pynecone-io/pynecone-examples/issues/92
Clean answers in default from on_load.

### CODE REVIEW

**Comment by milochen0418** [comment]
I don't know why 5 commits but Plz just squash merge it.

**Comment by jiangmiemie** [comment]
Glad you found this issue and fixed it, however issue 1 and issue 2 seem to need a fix as well. It is recommended to complete the submission at one time

**Comment by jiangmiemie** [comment]
> I don't know why 5 commits but Plz just squash merge it.

Glad you found this issue and fixed it, however question 1 and question 2 seem to need a fix as well(It should be mandatory to check one of them). It is recommended to complete the submission at one time

**Comment by milochen0418** [comment]
@jiangmiemie  This PR fixes the issue 
- https://github.com/pynecone-io/pynecone-examples/issues/84
If you find out some issue for Q1 and Q2, you can post it as issue and then solve it.

**Comment by milochen0418** [comment]
> > I don't know why 5 commits but Plz just squash merge it.
> 
> Glad you found this issue and fixed it, however question 1 and question 2 seem to need a fix as well(It should be mandatory to check one of them). It is recommended to complete the submission at one time 
@jiangmiemie 
I make issue #92 for your testing.  
And change the current PR's purpose from fixing #84 to fixing #84  and #92  together. 

Right now, the bug in the three questions has been fixed.

**Review by picklelo — APPROVED** [review]
nice!

**Pull request merged**
