### PR TITLE
[Fix 62] Enhance the user experience using the input field and the ad…

### PR DESCRIPTION
**Pull request by milochen0418**
This PR is related to this bug on todo example.
- https://github.com/pynecone-io/pynecone-examples/issues/62

Enhance the user experience of the input field.
- Add trim process for the input field. 
- show information on UI when the added item is duplicated in the current todo list.  
(Support it by window_alert now, but toast is better if we have)
- don't do anything when the input field is empty
- make the input field empty after the new item appears in the list.

### CODE REVIEW

**Comment by milochen0418** [comment]
Hi @Alek99: 
What should I improve for this pull request? 
I have no idea the way to make a pc.toast or any new component in the pynecone 

Do you have any suggestion or hint for me to do next? 
Thanks

**Comment by Alek99** [comment]
Sorry for the delayed review I'll look at this tonight

**Comment by milochen0418** [comment]
@Alek99 
The bug has happened when using on_blur. 
The code is not working for layout in add_item
```python
self.new_item = ""
```

The state has already changed, but the layout still shows the text.
So the second time to click the `Add` button, it will add a task with an empty name.

In the real code, we cannot use the following for the layout
```
value=State.new_item,
on_blur=State.set_new_item,
```

Finally, I found out we can use the following combination. 
```
value=State.new_item,
on_change=State.set_new_item,
```
So this way, ensure to fix bugs of 
- https://github.com/pynecone-io/pynecone-examples/issues/62

I also trim the input data in the code and avoid adding duplicated data.

**Comment by Alek99** [comment]
We do have the pc.form component out but not documented yet. I believe Nikhil is updating the docs soon. 

We may want to use this here. This will allow for clearing the input without having to use on change.


I'll post an update here when the documentation is updated.

**Comment by milochen0418** [comment]
> his will allow for clearing the input without having to use on change.
Wow, that sounds great. 

Maybe I can read your released document and implement todo example. 
Just like a tester whose native language is not English. 

If I can accomplish todo by reading the new document, I guess the document can also help more application developers to understand Pynecone quickly. When I read the document, I can also give feedback or help to improve the document.

**Comment by milochen0418** [comment]
@Alek99 
In the new pc.form for pc 0.1.32, the bug is still there. 
pc.input  doesn't  work for this example. 
Do you have plan to release new pc.input ?

**Comment by milochen0418** [comment]
> We do have the pc.form component out but not documented yet. I believe Nikhil is updating the docs soon.
> 
> We may want to use this here. This will allow for clearing the input without having to use on change.
> 
> I'll post an update here when the documentation is updated.

@Alek99
In the new pc.form for pc 0.1.32, the bug is still there.
pc.input doesn't work for this example.
Do you have plan to release any new pc.input?

**Comment by milochen0418** [comment]
We have this new code now for pc.form. 
So we don't need this old code anymore
- https://github.com/pynecone-io/pynecone-examples/pull/97

**Pull request closed without merging**
