### PR TITLE
Update CRM example

### PR DESCRIPTION
**Pull request by kbrgl**
https://user-images.githubusercontent.com/13417496/219604452-90c6da8a-d822-4437-a61f-94988a924dea.mov

### CODE REVIEW

**Comment by Alek99** [comment]
This sign up page seems to be not working for me, says `Looks like you’re already registered! Try logging in instead.` when there is blank input in the username password

**Comment by Alek99** [comment]
oh nvm my bad

**Comment by Alek99** [comment]
Can we do a separate signup page or make the sign up button more clear I initially though it was a link to a sign up page not a button to sign up with my given input

**Comment by kbrgl** [comment]
@Alek99 yes! Can do.

**Pull request closed without merging**
